# Generated by Django 3.2.3 on 2022-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
